"""
routers/scan.py
───────────────
Scan endpoints:
  POST /scan/url       Analyse a single URL
  POST /scan/email     Analyse email text or .eml content
  POST /scan/domain    Analyse a domain with DNS / WHOIS
  POST /scan/batch     Analyse up to 50 URLs in one request
"""

import asyncio
import logging
import re
import uuid
from datetime import datetime, timezone
from typing import Any, cast, Literal

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
import magic
import PyPDF2
from io import BytesIO
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth_middleware import get_current_user
from app.middleware.rate_limit import limiter
from app.models.scan import Scan
from app.models.scan_flag import ScanFlag
from app.models.user import User
from app.schemas.scan_schema import (
    BatchURLScanRequest,
    DomainScanRequest,
    DomainScanResult,
    EmailScanRequest,
    EmailScanResult,
    ScanResult,
    URLScanRequest,
)
from app.services import ai_service, dns_service, email_service, ml_service, intel_service
from app.schemas.scan_schema import FlagItem
from app.config import settings

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/scan", tags=["Scanning"])


# ── Internal helpers ──────────────────────────────────────────────────────────

async def _persist_scan(
    db: AsyncSession,
    user: User,
    scan_type: str,
    input_value: str,
    label: str,
    score: float,
    model_version: str,
    feature_values: dict,
    explanation: str | None,
    red_flags: list,
    green_flags: list,
) -> uuid.UUID:
    """
    Write a Scan row and its associated ScanFlag rows to the database.
    Returns the new scan UUID.
    """
    scan = Scan(
        user_id=user.id,
        scan_type=scan_type,
        input_value=input_value[:2048],
        label=label,
        score=round(score, 6),
        model_version=model_version,
        feature_values=feature_values,
        explanation=explanation,
    )
    db.add(scan)
    await db.flush()   # populate scan.id

    for flag in red_flags:
        db.add(ScanFlag(
            scan_id=scan.id,
            flag_type="red",
            flag_name=flag.flag_name,
            description=flag.description,
        ))
    for flag in green_flags:
        db.add(ScanFlag(
            scan_id=scan.id,
            flag_type="green",
            flag_name=flag.flag_name,
            description=flag.description,
        ))

    return scan.id


def _flag_dicts(flags: list) -> list[dict]:
    """Convert a list of FlagItem objects to plain dicts for ai_service."""
    return [{"flag_name": f.flag_name, "description": f.description} for f in flags]


# ── POST /scan/url ─────────────────────────────────────────────────────────────

@router.post(
    "/url",
    response_model=ScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse a single URL for phishing indicators",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_url(
    request: Request,
    body: URLScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ScanResult:
    """
    Run the XGBoost model against a single URL.

    Returns a classification label (phishing / suspicious / legitimate),
    a probability score, red and green flag chips, and a plain-English
    AI explanation generated by Gemini or Ollama.
    """
    url = body.url

    # Check Live Threat Intelligence (Layer 1)
    threat = await intel_service.lookup_threat(db, url)
    
    if threat:
        # Global Threat Match found
        # Map source to a nice display name
        source_map = {"phishtank": "PhishTank", "phishstats": "PhishStats", "urlhaus": "URLHaus"}
        source_name = source_map.get(threat.source, threat.source.capitalize())
        
        result = {
            "label": "phishing",
            "score": threat.confidence,
            "score_pct": round(threat.confidence * 100),
            "red_flags": [
                FlagItem(
                    flag_type="red",
                    flag_name="global_threat_match",
                    description=f"This URL is currently active on the {source_name} live threat feed."
                )
            ],
            "green_flags": [],
            "feature_values": {"threat_source": threat.source, "confidence": threat.confidence},
            "model_version": f"intel_feed_{threat.source}",
        }
    else:
        # No known threat found, fall back to XGBoost ML (Layer 2)
        result = ml_service.predict_url(url)

    # AI explanation (run concurrently with DB write)
    r_label       = cast(Literal["legitimate", "phishing", "suspicious"], result["label"])
    r_score       = cast(float, result["score"])
    r_score_pct   = cast(int, result["score_pct"])
    r_red_flags   = cast(list, result["red_flags"])
    r_green_flags = cast(list, result["green_flags"])
    r_model_ver   = cast(str, result["model_version"])
    r_features    = cast(dict[str, Any], result.get("feature_values", {}))
    r_shap        = cast(dict[str, Any] | None, result.get("shap_values"))

    explanation, scan_id = await asyncio.gather(
        ai_service.generate_explanation(
            input_value=url,
            label=r_label,
            score_pct=r_score_pct,
            red_flags=_flag_dicts(r_red_flags),
            green_flags=_flag_dicts(r_green_flags),
            feature_values=r_shap,
        ),
        _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=r_label,
            score=r_score,
            model_version=r_model_ver,
            feature_values=r_features,
            explanation=None,   # updated below after gather
            red_flags=r_red_flags,
            green_flags=r_green_flags,
        ),
    )

    # Patch explanation into the persisted row
    scan_obj = await db.get(Scan, scan_id)
    if scan_obj:
        scan_obj.explanation = explanation

    logger.info(
        "URL scan: user=%s url=%s label=%s score=%.2f",
        current_user.id, url[:80], r_label, r_score,
    )

    return ScanResult(
        scan_id=scan_id,
        input_value=url,
        label=r_label,
        score=r_score,
        score_pct=r_score_pct,
        red_flags=r_red_flags,
        green_flags=r_green_flags,
        feature_values=r_features,
        explanation=explanation,
        model_version=r_model_ver,
        scanned_at=datetime.now(tz=timezone.utc),
    )


# ── POST /scan/email ──────────────────────────────────────────────────────────

async def _do_scan_email(
    request: Request,
    body: EmailScanRequest,
    db: AsyncSession,
    current_user: User,
    pre_extracted_urls: list[str] | None = None,
) -> EmailScanResult:
    """
    Internal helper that performs raw email text analysis or processes pre-extracted URLs.
    """
    raw_text = body.text

    # Extract URLs from visible text
    text_urls = email_service.extract_urls_from_text(raw_text)
    # Merge with pre-extracted annotation URLs (deduplicated)
    seen: set[str] = set(text_urls)
    extra_urls: list[str] = []
    for u in (pre_extracted_urls or []):
        if u not in seen:
            seen.add(u)
            extra_urls.append(u)
    extracted_urls = text_urls + extra_urls

    # Score email text
    email_score_data = email_service.score_email_text("", raw_text)

    # Score each URL (cap at 50 to handle PDFs with many hyperlinks)
    url_results: list[ScanResult] = []
    url_scores: list[float] = []
    for url in extracted_urls[:50]:
        url_ml = ml_service.predict_url(url)
        url_scan_id = await _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=url_ml["label"],
            score=url_ml["score"],
            model_version=url_ml["model_version"],
            feature_values=url_ml.get("feature_values", {}),
            explanation=None,
            red_flags=url_ml["red_flags"],
            green_flags=url_ml["green_flags"],
        )
        url_scores.append(url_ml["score"])
        url_results.append(ScanResult(
            scan_id=url_scan_id,
            input_value=url,
            label=url_ml["label"],
            score=url_ml["score"],
            score_pct=url_ml["score_pct"],
            red_flags=url_ml["red_flags"],
            green_flags=url_ml["green_flags"],
            feature_values=url_ml.get("feature_values"),
            explanation=None,
            model_version=url_ml["model_version"],
            scanned_at=datetime.now(tz=timezone.utc),
        ))

    # Combine scores
    overall_score = email_service.combine_email_and_url_scores(
        email_score_data["ml_score"], url_scores
    )
    overall_score_pct = round(overall_score * 100)
    _raw_label    = ml_service._score_to_label(overall_score)
    overall_label = cast(Literal["legitimate", "phishing", "suspicious"], _raw_label)

    # Merge email + URL flags
    all_red = email_score_data["red_flags"] + email_service._sender_domain_mismatch(raw_text, extracted_urls)
    all_green = email_score_data["green_flags"]

    # AI explanation
    explanation = await ai_service.generate_explanation(
        input_value=raw_text[:200],
        label=overall_label,
        score_pct=overall_score_pct,
        red_flags=_flag_dicts(all_red),
        green_flags=_flag_dicts(all_green),
    )

    # Persist the top-level email scan
    email_scan_id = await _persist_scan(
        db=db,
        user=current_user,
        scan_type="email",
        input_value=raw_text[:500],
        label=overall_label,
        score=overall_score,
        model_version="email_lr_v1",
        feature_values={"email_ml_score": email_score_data["ml_score"]},
        explanation=explanation,
        red_flags=all_red,
        green_flags=all_green,
    )

    logger.info(
        "Email scan: user=%s label=%s score=%.2f urls_found=%d",
        current_user.id, overall_label, overall_score, len(extracted_urls),
    )

    return EmailScanResult(
        scan_id=email_scan_id,
        overall_label=overall_label,
        overall_score=overall_score,
        overall_score_pct=overall_score_pct,
        red_flags=all_red,
        green_flags=all_green,
        extracted_urls=url_results,
        explanation=explanation,
        scanned_at=datetime.now(tz=timezone.utc),
    )


@router.post(
    "/email",
    response_model=EmailScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse raw email text for phishing indicators",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_email(
    request: Request,
    body: EmailScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> EmailScanResult:
    """
    Accepts raw email text (subject + body paste).
    """
    return await _do_scan_email(
        request=request,
        body=body,
        db=db,
        current_user=current_user,
        pre_extracted_urls=None,
    )


# ── POST /scan/email (file upload variant) ───────────────────────────────────

@router.post(
    "/email/upload",
    response_model=EmailScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse an uploaded .pdf or .txt email file",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_email_file(
    request: Request,
    file: UploadFile = File(..., description="Raw .pdf or .txt email file"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> EmailScanResult:
    """
    Parse an uploaded .pdf or plain text file, then delegate to scan_email logic.
    File size is limited to 1 MB.
    """
    filename = file.filename.lower() if file.filename else ""
    if not filename.endswith('.pdf'):
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only PDF files (.pdf) are accepted for upload. Copy-paste plain email text into the Email Scan field instead."
        )

    MAX_SIZE = 1_048_576   # 1 MB
    raw_bytes = await file.read()
    if len(raw_bytes) > MAX_SIZE:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="File must be smaller than 1 MB",
        )

    # Use magic-bytes to verify file content type (mitigates renamed malicious files)
    mime = magic.Magic(mime=True)
    detected_mime = mime.from_buffer(raw_bytes)
    
    allowed_mimes = {"application/pdf"}
    if detected_mime not in allowed_mimes:
        logger.warning("Rejected file upload with suspicious mime type: %s", detected_mime)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Only PDF files are accepted. The uploaded file's content does not appear to be a valid PDF."
        )

    # ── Extract text and ALL hyperlinks from the PDF ──────────────────────────
    if detected_mime == "application/pdf":
        try:
            pdf_reader = PyPDF2.PdfReader(BytesIO(raw_bytes))
            combined = ""
            annotation_links: list[str] = []

            for page_num, page in enumerate(pdf_reader.pages):
                # 1. Extract visible text from this page
                text = page.extract_text() or ""
                combined += text + "\n"

                # 2. Walk /Annots to find ALL hyperlinked URLs (hidden behind text)
                #    This catches links like "Billing Address", "Click here", etc.
                raw_annots = page.get("/Annots")
                if raw_annots is None:
                    continue
                try:
                    # May be an ArrayObject or an IndirectObject pointing to one
                    if hasattr(raw_annots, "get_object"):
                        raw_annots = raw_annots.get_object()

                    for annot_ref in raw_annots:
                        try:
                            annot_obj = annot_ref.get_object() if hasattr(annot_ref, "get_object") else annot_ref
                        except Exception:
                            continue

                        if annot_obj.get("/Subtype") != "/Link":
                            continue

                        action = annot_obj.get("/A")
                        if action is None:
                            continue

                        try:
                            action_obj = action.get_object() if hasattr(action, "get_object") else action
                        except Exception:
                            continue

                        # Only process URI actions (not GoTo, Named, etc.)
                        if action_obj.get("/S") != "/URI":
                            continue

                        uri_raw = action_obj.get("/URI")
                        if not uri_raw:
                            continue

                        uri = str(uri_raw).strip()
                        # Only keep valid http/https URLs; skip PDF bookmarks / mailto
                        if re.match(r"^https?://", uri, re.IGNORECASE):
                            annotation_links.append(uri)

                except Exception as ann_err:
                    logger.warning("PDF page %d annotation parse error: %s", page_num, ann_err)

            # Deduplicate annotation links while preserving order
            seen_annot: set[str] = set()
            unique_annot_links: list[str] = []
            for link in annotation_links:
                if link not in seen_annot:
                    seen_annot.add(link)
                    unique_annot_links.append(link)

            logger.info(
                "PDF parse complete: %d chars text, %d annotation hyperlinks found",
                len(combined), len(unique_annot_links),
            )

            if not combined.strip() and not unique_annot_links:
                combined = "No readable text or hyperlinks found in this PDF."

        except Exception as e:
            logger.error("Error parsing PDF: %s", e, exc_info=True)
            raise HTTPException(status_code=400, detail="Could not extract text from PDF")

    else:
        unique_annot_links = []
        # Parse plain text file content
        try:
            combined = raw_bytes.decode("utf-8")
        except UnicodeDecodeError:
            try:
                combined = raw_bytes.decode("latin-1")
            except Exception:
                raise HTTPException(status_code=400, detail="Could not decode text file content")

    return await _do_scan_email(
        request=request,
        body=EmailScanRequest(text=combined),
        db=db,
        current_user=current_user,
        pre_extracted_urls=unique_annot_links,
    )


# ── POST /scan/domain ─────────────────────────────────────────────────────────

@router.post(
    "/domain",
    response_model=DomainScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse a domain with DNS, WHOIS, and ML-based risk assessment",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_domain(
    request: Request,
    body: DomainScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> DomainScanResult:
    """
    Full domain analysis:
      - A / MX / NS DNS records
      - WHOIS (registrar, domain age)
      - Geo-IP of hosting server
      - SSL certificate issuer
      - ML risk score on the domain string
      - AI plain-English explanation
    """
    domain = body.domain

    # Run the full DNS + ML analysis
    analysis = await dns_service.analyse_domain(domain)

    # AI explanation
    explanation = await ai_service.generate_explanation(
        input_value=domain,
        label=analysis["label"],
        score_pct=analysis["score_pct"],
        red_flags=_flag_dicts(analysis["red_flags"]),
        green_flags=_flag_dicts(analysis["green_flags"]),
    )

    # Persist
    scan_id = await _persist_scan(
        db=db,
        user=current_user,
        scan_type="domain",
        input_value=domain,
        label=analysis["label"],
        score=analysis["score"],
        model_version=analysis.get("model_version", "xgb_v1"),
        feature_values={"domain": domain},
        explanation=explanation,
        red_flags=analysis["red_flags"],
        green_flags=analysis["green_flags"],
    )

    logger.info(
        "Domain scan: user=%s domain=%s label=%s score=%.2f",
        current_user.id, domain, analysis["label"], analysis["score"],
    )

    return DomainScanResult(
        scan_id=scan_id,
        domain=domain,
        label=analysis["label"],
        score=analysis["score"],
        score_pct=analysis["score_pct"],
        dns_info=analysis["dns_info"],
        red_flags=analysis["red_flags"],
        green_flags=analysis["green_flags"],
        explanation=explanation,
        scanned_at=datetime.now(tz=timezone.utc),
    )


# ── POST /scan/batch ──────────────────────────────────────────────────────────

@router.post(
    "/batch",
    response_model=list[ScanResult],
    status_code=status.HTTP_200_OK,
    summary="Batch-scan up to 50 URLs in a single request",
)
@limiter.limit("5/hour")     # stricter limit for batch
async def scan_batch(
    request: Request,
    body: BatchURLScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[ScanResult]:
    """
    Analyse a list of URLs concurrently using asyncio.gather.
    Returns one ScanResult per URL in the same order as the input list.
    Batch requests are limited to 5 per hour (regardless of the per-URL limit).
    """
    results = []
    for url in body.urls[:50]:
        result = ml_service.predict_url(url)
        scan_id = await _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=result["label"],
            score=result["score"],
            model_version=result["model_version"],
            feature_values=result.get("feature_values", {}),
            explanation=None,
            red_flags=result["red_flags"],
            green_flags=result["green_flags"],
        )
        results.append(
            ScanResult(
                scan_id=scan_id,
                input_value=url,
                label=result["label"],
                score=result["score"],
                score_pct=result["score_pct"],
                red_flags=result["red_flags"],
                green_flags=result["green_flags"],
                feature_values=result.get("feature_values"),
                explanation=None,   # omitted for batch to keep responses fast
                model_version=result["model_version"],
                scanned_at=datetime.now(tz=timezone.utc),
            )
        )

    logger.info(
        "Batch scan: user=%s urls=%d", current_user.id, len(body.urls)
    )
    return results