"""
routers/scan.py
───────────────
Scan endpoints:
  POST /scan/url       Analyse a single URL
  POST /scan/email     Analyse email text or .eml content
  POST /scan/domain    Analyse a domain with DNS / WHOIS
  POST /scan/batch     Analyse up to 50 URLs in one request
"""

import asyncio
import logging
import uuid
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, File, HTTPException, Request, UploadFile, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.middleware.auth_middleware import get_current_user
from app.middleware.rate_limit import limiter
from app.models.scan import Scan
from app.models.scan_flag import ScanFlag
from app.models.user import User
from app.schemas.scan_schema import (
    BatchURLScanRequest,
    DomainScanRequest,
    DomainScanResult,
    EmailScanRequest,
    EmailScanResult,
    ScanResult,
    URLScanRequest,
)
from app.services import ai_service, dns_service, email_service, ml_service, intel_service
from app.schemas.scan_schema import FlagItem
from app.config import settings

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/scan", tags=["Scanning"])


# ── Internal helpers ──────────────────────────────────────────────────────────

async def _persist_scan(
    db: AsyncSession,
    user: User,
    scan_type: str,
    input_value: str,
    label: str,
    score: float,
    model_version: str,
    feature_values: dict,
    explanation: str | None,
    red_flags: list,
    green_flags: list,
) -> uuid.UUID:
    """
    Write a Scan row and its associated ScanFlag rows to the database.
    Returns the new scan UUID.
    """
    scan = Scan(
        user_id=user.id,
        scan_type=scan_type,
        input_value=input_value[:2048],
        label=label,
        score=round(score, 6),
        model_version=model_version,
        feature_values=feature_values,
        explanation=explanation,
    )
    db.add(scan)
    await db.flush()   # populate scan.id

    for flag in red_flags:
        db.add(ScanFlag(
            scan_id=scan.id,
            flag_type="red",
            flag_name=flag.flag_name,
            description=flag.description,
        ))
    for flag in green_flags:
        db.add(ScanFlag(
            scan_id=scan.id,
            flag_type="green",
            flag_name=flag.flag_name,
            description=flag.description,
        ))

    return scan.id


def _flag_dicts(flags: list) -> list[dict]:
    """Convert a list of FlagItem objects to plain dicts for ai_service."""
    return [{"flag_name": f.flag_name, "description": f.description} for f in flags]


# ── POST /scan/url ─────────────────────────────────────────────────────────────

@router.post(
    "/url",
    response_model=ScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse a single URL for phishing indicators",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_url(
    request: Request,
    body: URLScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> ScanResult:
    """
    Run the XGBoost model against a single URL.

    Returns a classification label (phishing / suspicious / legitimate),
    a probability score, red and green flag chips, and a plain-English
    AI explanation generated by Gemini or Ollama.
    """
    url = body.url

    # Check Live Threat Intelligence (Layer 1)
    threat = await intel_service.lookup_threat(db, url)
    
    if threat:
        # Global Threat Match found
        # Map source to a nice display name
        source_map = {"phishtank": "PhishTank", "phishstats": "PhishStats", "urlhaus": "URLHaus"}
        source_name = source_map.get(threat.source, threat.source.capitalize())
        
        result = {
            "label": "phishing",
            "score": threat.confidence,
            "score_pct": int(round(threat.confidence * 100)),
            "red_flags": [
                FlagItem(
                    flag_type="red",
                    flag_name="global_threat_match",
                    description=f"This URL is currently active on the {source_name} live threat feed."
                )
            ],
            "green_flags": [],
            "feature_values": {"threat_source": threat.source, "confidence": threat.confidence},
            "model_version": f"intel_feed_{threat.source}",
        }
    else:
        # No known threat found, fall back to XGBoost ML (Layer 2)
        result = ml_service.predict_url(url)

    # AI explanation (run concurrently with DB write)
    explanation, scan_id = await asyncio.gather(
        ai_service.generate_explanation(
            input_value=url,
            label=result["label"],
            score_pct=result["score_pct"],
            red_flags=_flag_dicts(result["red_flags"]),
            green_flags=_flag_dicts(result["green_flags"]),
            feature_values=result.get("shap_values"),
        ),
        _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=result["label"],
            score=result["score"],
            model_version=result["model_version"],
            feature_values=result.get("feature_values", {}),
            explanation=None,   # updated below after gather
            red_flags=result["red_flags"],
            green_flags=result["green_flags"],
        ),
    )

    # Patch explanation into the persisted row
    scan_obj = await db.get(Scan, scan_id)
    if scan_obj:
        scan_obj.explanation = explanation

    logger.info(
        "URL scan: user=%s url=%s label=%s score=%.2f",
        current_user.id, url[:80], result["label"], result["score"],
    )

    return ScanResult(
        scan_id=scan_id,
        input_value=url,
        label=result["label"],
        score=result["score"],
        score_pct=result["score_pct"],
        red_flags=result["red_flags"],
        green_flags=result["green_flags"],
        feature_values=result.get("feature_values"),
        explanation=explanation,
        model_version=result["model_version"],
        scanned_at=datetime.now(tz=timezone.utc),
    )


# ── POST /scan/email ──────────────────────────────────────────────────────────

@router.post(
    "/email",
    response_model=EmailScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse raw email text for phishing indicators",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_email(
    request: Request,
    body: EmailScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> EmailScanResult:
    """
    Accepts raw email text (subject + body paste).

    Steps:
      1. Extract all embedded URLs.
      2. Score email text via TF-IDF + Logistic Regression.
      3. Score each URL via XGBoost.
      4. Combine scores (40% email + 60% max URL score).
      5. Generate an AI explanation.
    """
    raw_text = body.text

    # Extract URLs
    extracted_urls = email_service.extract_urls_from_text(raw_text)

    # Score email text
    email_score_data = email_service.score_email_text("", raw_text)

    # Score each URL
    url_results: list[ScanResult] = []
    url_scores: list[float] = []
    for url in extracted_urls[:20]:   # cap at 20 URLs per email
        url_ml = ml_service.predict_url(url)
        url_scan_id = await _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=url_ml["label"],
            score=url_ml["score"],
            model_version=url_ml["model_version"],
            feature_values=url_ml.get("feature_values", {}),
            explanation=None,
            red_flags=url_ml["red_flags"],
            green_flags=url_ml["green_flags"],
        )
        url_scores.append(url_ml["score"])
        url_results.append(ScanResult(
            scan_id=url_scan_id,
            input_value=url,
            label=url_ml["label"],
            score=url_ml["score"],
            score_pct=url_ml["score_pct"],
            red_flags=url_ml["red_flags"],
            green_flags=url_ml["green_flags"],
            feature_values=url_ml.get("feature_values"),
            explanation=None,
            model_version=url_ml["model_version"],
            scanned_at=datetime.now(tz=timezone.utc),
        ))

    # Combine scores
    overall_score = email_service.combine_email_and_url_scores(
        email_score_data["ml_score"], url_scores
    )
    overall_score_pct = int(round(overall_score * 100))
    overall_label = ml_service._score_to_label(overall_score)

    # Merge email + URL flags
    all_red = email_score_data["red_flags"] + email_service._sender_domain_mismatch(raw_text, extracted_urls)
    all_green = email_score_data["green_flags"]

    # AI explanation
    explanation = await ai_service.generate_explanation(
        input_value=raw_text[:200],
        label=overall_label,
        score_pct=overall_score_pct,
        red_flags=_flag_dicts(all_red),
        green_flags=_flag_dicts(all_green),
    )

    # Persist the top-level email scan
    email_scan_id = await _persist_scan(
        db=db,
        user=current_user,
        scan_type="email",
        input_value=raw_text[:500],
        label=overall_label,
        score=overall_score,
        model_version="email_lr_v1",
        feature_values={"email_ml_score": email_score_data["ml_score"]},
        explanation=explanation,
        red_flags=all_red,
        green_flags=all_green,
    )

    logger.info(
        "Email scan: user=%s label=%s score=%.2f urls_found=%d",
        current_user.id, overall_label, overall_score, len(extracted_urls),
    )

    return EmailScanResult(
        scan_id=email_scan_id,
        overall_label=overall_label,
        overall_score=overall_score,
        overall_score_pct=overall_score_pct,
        red_flags=all_red,
        green_flags=all_green,
        extracted_urls=url_results,
        explanation=explanation,
        scanned_at=datetime.now(tz=timezone.utc),
    )


# ── POST /scan/email (file upload variant) ───────────────────────────────────

@router.post(
    "/email/upload",
    response_model=EmailScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse an uploaded .eml or .txt email file",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_email_file(
    request: Request,
    file: UploadFile = File(..., description="Raw .eml or .txt email file"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> EmailScanResult:
    """
    Parse an uploaded .eml or plain text file, then delegate to scan_email logic.
    File size is limited to 1 MB.
    """
    MAX_SIZE = 1_048_576   # 1 MB
    raw_bytes = await file.read()
    if len(raw_bytes) > MAX_SIZE:
        raise HTTPException(
            status_code=status.HTTP_413_REQUEST_ENTITY_TOO_LARGE,
            detail="File must be smaller than 1 MB",
        )

    allowed = {"text/plain", "message/rfc822", "application/octet-stream"}
    if file.content_type not in allowed and not (
        file.filename or ""
    ).endswith((".eml", ".txt")):
        raise HTTPException(
            status_code=status.HTTP_415_UNSUPPORTED_MEDIA_TYPE,
            detail="Only .eml or .txt files are accepted",
        )

    # Parse .eml headers and body
    subject, body = email_service.parse_eml(raw_bytes)
    combined = f"Subject: {subject}\n\n{body}"

    return await scan_email(
        request=request,
        body=EmailScanRequest(text=combined),
        db=db,
        current_user=current_user,
    )


# ── POST /scan/domain ─────────────────────────────────────────────────────────

@router.post(
    "/domain",
    response_model=DomainScanResult,
    status_code=status.HTTP_200_OK,
    summary="Analyse a domain with DNS, WHOIS, and ML-based risk assessment",
)
@limiter.limit(settings.SCAN_RATE_LIMIT)
async def scan_domain(
    request: Request,
    body: DomainScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> DomainScanResult:
    """
    Full domain analysis:
      - A / MX / NS DNS records
      - WHOIS (registrar, domain age)
      - Geo-IP of hosting server
      - SSL certificate issuer
      - ML risk score on the domain string
      - AI plain-English explanation
    """
    domain = body.domain

    # Run the full DNS + ML analysis
    analysis = await dns_service.analyse_domain(domain)

    # AI explanation
    explanation = await ai_service.generate_explanation(
        input_value=domain,
        label=analysis["label"],
        score_pct=analysis["score_pct"],
        red_flags=_flag_dicts(analysis["red_flags"]),
        green_flags=_flag_dicts(analysis["green_flags"]),
    )

    # Persist
    scan_id = await _persist_scan(
        db=db,
        user=current_user,
        scan_type="domain",
        input_value=domain,
        label=analysis["label"],
        score=analysis["score"],
        model_version=analysis.get("model_version", "xgb_v1"),
        feature_values={"domain": domain},
        explanation=explanation,
        red_flags=analysis["red_flags"],
        green_flags=analysis["green_flags"],
    )

    logger.info(
        "Domain scan: user=%s domain=%s label=%s score=%.2f",
        current_user.id, domain, analysis["label"], analysis["score"],
    )

    return DomainScanResult(
        scan_id=scan_id,
        domain=domain,
        label=analysis["label"],
        score=analysis["score"],
        score_pct=analysis["score_pct"],
        dns_info=analysis["dns_info"],
        red_flags=analysis["red_flags"],
        green_flags=analysis["green_flags"],
        explanation=explanation,
        scanned_at=datetime.now(tz=timezone.utc),
    )


# ── POST /scan/batch ──────────────────────────────────────────────────────────

@router.post(
    "/batch",
    response_model=list[ScanResult],
    status_code=status.HTTP_200_OK,
    summary="Batch-scan up to 50 URLs in a single request",
)
@limiter.limit("5/hour")     # stricter limit for batch
async def scan_batch(
    request: Request,
    body: BatchURLScanRequest,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
) -> list[ScanResult]:
    """
    Analyse a list of URLs concurrently using asyncio.gather.
    Returns one ScanResult per URL in the same order as the input list.
    Batch requests are limited to 5 per hour (regardless of the per-URL limit).
    """
    async def _scan_one(url: str) -> ScanResult:
        result = ml_service.predict_url(url)
        scan_id = await _persist_scan(
            db=db,
            user=current_user,
            scan_type="url",
            input_value=url,
            label=result["label"],
            score=result["score"],
            model_version=result["model_version"],
            feature_values=result.get("feature_values", {}),
            explanation=None,
            red_flags=result["red_flags"],
            green_flags=result["green_flags"],
        )
        return ScanResult(
            scan_id=scan_id,
            input_value=url,
            label=result["label"],
            score=result["score"],
            score_pct=result["score_pct"],
            red_flags=result["red_flags"],
            green_flags=result["green_flags"],
            feature_values=result.get("feature_values"),
            explanation=None,   # omitted for batch to keep responses fast
            model_version=result["model_version"],
            scanned_at=datetime.now(tz=timezone.utc),
        )

    results = await asyncio.gather(*[_scan_one(u) for u in body.urls[:50]])
    logger.info(
        "Batch scan: user=%s urls=%d", current_user.id, len(body.urls)
    )
    return list(results)