"""fix_missing_scan_columns

Revision ID: 28ed1f886ddf
Revises: add_role_token_attempts
Create Date: 2026-04-29 20:04:00.710213+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28ed1f886ddf'
down_revision: Union[str, None] = 'add_role_token_attempts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add scan_type with a temporary nullable=True to handle existing rows
    op.add_column('scans', sa.Column('scan_type', sa.Enum('url', 'email', 'domain', name='scan_type_enum'), nullable=True))
    op.execute("UPDATE scans SET scan_type = 'url'")
    op.alter_column('scans', 'scan_type', nullable=False)

    # Add label with a temporary nullable=True
    op.add_column('scans', sa.Column('label', sa.Enum('phishing', 'legitimate', 'suspicious', name='label_enum'), nullable=True))
    op.execute("UPDATE scans SET label = 'phishing' WHERE score >= 0.5")
    op.execute("UPDATE scans SET label = 'legitimate' WHERE score < 0.5")
    op.alter_column('scans', 'label', nullable=False)

    # Drop the unnecessary unique constraint on url (handled by hash index)
    op.execute("ALTER TABLE threat_intel DROP CONSTRAINT IF EXISTS threat_intel_url_key")

    # Keep server defaults for users table (avoiding unnecessary noise from autogenerate)
    # op.alter_column('users', 'role', ...) 
    # op.alter_column('users', 'verify_token_attempts', ...)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verify_token_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_role_enum'),
               server_default=sa.text("'user'::user_role_enum"),
               existing_nullable=False)
    op.create_index(op.f('threat_intel_url_key'), 'threat_intel', [sa.literal_column('md5(url)')], unique=True)
    op.drop_column('scans', 'label')
    op.drop_column('scans', 'scan_type')
    # ### end Alembic commands ###
