"""add_ai_quota_columns_to_users

Revision ID: 737f5b145788
Revises: 999ad4909727
Create Date: 2026-07-12 15:33:05.971273+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '737f5b145788'
down_revision: Union[str, None] = '999ad4909727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_intel_url_hash'), table_name='threat_intel')
    op.create_index('ix_threat_intel_url_hash', 'threat_intel', ['url'], unique=False)
    op.add_column('users', sa.Column('tier', sa.String(length=50), server_default='free', nullable=False))
    op.add_column('users', sa.Column('daily_ai_token_quota', sa.Integer(), server_default='25000', nullable=False))
    op.add_column('users', sa.Column('ai_tokens_used_today', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_token_reset', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_token_reset')
    op.drop_column('users', 'ai_tokens_used_today')
    op.drop_column('users', 'daily_ai_token_quota')
    op.drop_column('users', 'tier')
    op.drop_index('ix_threat_intel_url_hash', table_name='threat_intel')
    op.create_index(op.f('ix_threat_intel_url_hash'), 'threat_intel', [sa.literal_column('md5(url)')], unique=False)
    # ### end Alembic commands ###
