"""Add threat_intel table

Revision ID: 49822a0524f2
Revises: 0578e5554872
Create Date: 2026-04-11 11:08:24.150841+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49822a0524f2'
down_revision: Union[str, None] = '0578e5554872'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_intel',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('target_brand', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_threat_intel_created_at'), 'threat_intel', ['created_at'], unique=False)
    op.create_index('ix_threat_intel_url_hash', 'threat_intel', ['url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_threat_intel_url_hash', table_name='threat_intel')
    op.drop_index(op.f('ix_threat_intel_created_at'), table_name='threat_intel')
    op.drop_table('threat_intel')
    # ### end Alembic commands ###
