"""add_totp_fields_to_users

Revision ID: 21638621b377
Revises: 28ed1f886ddf
Create Date: 2026-06-20 15:04:33.620528+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21638621b377'
down_revision: Union[str, None] = '28ed1f886ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_index(op.f('threat_intel_url_key'), table_name='threat_intel', if_exists=True)
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))

    # Add totp_enabled with a server_default so existing rows get FALSE
    op.add_column('users', sa.Column(
        'totp_enabled', sa.Boolean(), nullable=False,
        server_default=sa.text('false')
    ))
    # Remove the server_default — application code supplies the value going forward
    op.alter_column('users', 'totp_enabled', server_default=None)

    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_role_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'verify_token_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'verify_token_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'admin', name='user_role_enum'),
               server_default=sa.text("'user'::user_role_enum"),
               existing_nullable=False)
    op.drop_column('users', 'totp_enabled')
    op.drop_column('users', 'totp_secret')
    op.create_index(op.f('threat_intel_url_key'), 'threat_intel', [sa.literal_column('md5(url)')], unique=True)
    # ### end Alembic commands ###
